CREATE SCHEMA IF NOT EXISTS `americanBlack` DEFAULT CHARACTER SET utf8 ;
USE `americanBlack` ;

CREATE TABLE IF NOT EXISTS `americanBlack`.`TIPO_USUARIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `americanBlack`.`USUARIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(60) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `TIPO_USUARIO_id` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_USUARIO_TIPO_USUARIO`
    FOREIGN KEY (`TIPO_USUARIO_id`)
    REFERENCES `americanBlack`.`TIPO_USUARIO` (`id`)
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `americanBlack`.`PRODUCTO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `stock` INT NULL,
  `VALOR` DECIMAL(2) NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `americanBlack`.`CARRITO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `PRODUCTO_id` INT NOT NULL,
  `USUARIO_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CARRITO_PRODUCTO1_idx` (`PRODUCTO_id`),
  INDEX `fk_CARRITO_USUARIO1_idx` (`USUARIO_id`),
  CONSTRAINT `fk_CARRITO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id`)
    REFERENCES `americanBlack`.`PRODUCTO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARRITO_USUARIO1`
    FOREIGN KEY (`USUARIO_id`)
    REFERENCES `americanBlack`.`USUARIO` (`id`)
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `americanBlack`.`FACTURA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `total` DECIMAL(2) NULL,
  `CARRITO_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_FACTURA_CARRITO1_idx` (`CARRITO_id`),
  CONSTRAINT `fk_FACTURA_CARRITO1`
    FOREIGN KEY (`CARRITO_id`)
    REFERENCES `americanBlack`.`CARRITO` (`id`)
)
ENGINE = InnoDB;